export const DREAM_MAJORS = [
  "Geological Engineering (FITB)",
  "Geodesy and Geomatics Engineering (FITB)",
  "Actuarial Science",
  "Mathematics (FMIPA)",
  "Physics (FMIPA)",
  "Chemistry (FMIPA)",
  "Visual Communication Design (FSRD)",
  "Product Design (FSRD)",
  "Craft (FSRD)",
  "Engineering Physics (FTI)",
  "Industrian Engineering (FTI)",
  "Chemical Engineering (FTI)",
  "Aerospace Engineering (FTMD)",
  "Mechanical Engineering (FTMD)",
  "Environmental Engineering (FTSL)",
  "Metallurgical Engineering (FTTM)",
  "Architecture (SAPPK)",
  "Entrepreneurship (SBM)",
  "Management (SBM)",
  "Clinical and Community Pharmacy (SF)",
  "Pharmaceutical Science and Technology (SF)",
  "Biology - Marine and Coastal Biology (SITH)",
  "Biology - Biomedical Science (SITH)",
  "Information System and Technology (STEI)",
  "Informatics (STEI)",
  "Telecommunication Engineering(STEI)",
  "Electrical Power Engineering (STEI)",
  "Electrical Engineering (STEI)",
] as const;
